<?php
    $fields = array(
        'component_tile' => array(
            'key' => 'component_tile',
            'name' => 'tile',
            'label' => 'Tile',
            'display' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'component_tile_tab_general',
                    'label' => 'General',
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                ),
                array(
                    'key' => 'component_tile_enable',
                    'label' => 'Enable',
                    'name' => 'counter_enable',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '',
                    'default_value' => 1,
                    'ui' => 1,
                    'ui_on_text' => '',
                    'ui_off_text' => '',
                ),
                array(
                    'key' => 'component_tile_id',
                    'label' => 'ID',
                    'name' => 'id',
                    'type' => 'text',
                    'instructions' => 'identifier',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                ),
                array(
                    'key' => 'component_tile_class',
                    'label' => 'Classes',
                    'name' => 'class',
                    'type' => 'text',
                    'instructions' => 'additional classes',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                ),
                array(
                    'key' => 'component_tile_tab_settings',
                    'label' => 'Settings',
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                ),
                array(
                    'key' => 'component_tile_title',
                    'label' => 'Title',
                    'name' => 'title',
                    'type' => 'text',
                    'instructions' => '&nbsp;',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                ),
                array(
                    'key' => 'component_tile_subtitle',
                    'label' => 'Subtitle',
                    'name' => 'subtitle',
                    'type' => 'text',
                    'instructions' => '&nbsp;',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                ),
                array(
                    'key' => 'component_tile_percentage',
                    'label' => 'Percentage',
                    'name' => 'percentage',
                    'type' => 'repeater',
                    'instructions' => '&nbsp;',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'min' => 1,
                    'max' => 0,
                    'layout' => 'block',
                    'sub_fields' => array(
                        array(
                            'key' => 'component_tile_selectdata',
                            'label' => 'Select option',
                            'name' => 'radio',
                            'type' => 'radio',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                'percent' => 'Percent',
                                'number' => 'Number',
                            ),
                            'allow_null' => 0,
                            'other_choice' => 0,
                            'default_value' => 'percent',
                            'layout' => 'horizontal',
                            'return_format' => 'value',
                            'save_other_choice' => 0,
                        ),
                        array(
                            'key' => 'component_tile_percent',
                            'label' => 'Percent',
                            'name' => 'percent',
                            'type' => 'range',
                            'required' => 0,
                            'default' => 0,
                            'conditional_logic' => array(
                                array(
                                    array(
                                        'field' => 'component_tile_selectdata',
                                        'operator' => '==',
                                        'value' => 'percent',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'minimum' => 0,
                            'maximum' => 100,
                            'step_size' => 1,
                            'append' => '%',
                            'prepend' => '',
                        ),
                        array(
                            'key' => 'component_tile_number',
                            'label' => 'Number',
                            'name' => 'number',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                array(
                                    array(
                                        'field' => 'component_tile_selectdata',
                                        'operator' => '==',
                                        'value' => 'number',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array(
                            'key' => 'component_tile_desc',
                            'label' => 'Body',
                            'name' => 'body',
                            'name' => 'body',
                            'type' => 'wysiwyg',
                            'instructions' => '',
                            'required' => 0,
                            'wrapper' => array(
                                'width' => '100',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'tabs' => '',
                            'toolbar' => 'basic',
                            'media_upload' => 1,
                            'delay' => 1,
                        )
                    )
                )
            )
        )
    );
